### PR TITLE
Modifications from the mob programming session on 29/05

### PR DESCRIPTION
**Pull request by mishrsud**
Modifications from the mob programming session on 29/05

### CODE REVIEW

**Comment by mderriey** [comment]
Yo!

Thanks for opening this. I pulled the branch and it doesn't build as we removed the `Id` from the `DiaryNote` constructor and both the tests and the API depend on this.

We either need to do additional changes to cater for this or undo these changes.

I think a collective decision would be nice: @random82 @rbanks54 @IbraheemOsama @maxgherman @ahmad2x4 @sviridovserg

Hopefully I didn't forget anyone :-)

**Comment by abowen** [comment]
Interesting approach, I like it.

**Comment by mderriey** [comment]
Hey @mishrsud I pushed some changes to fix the build and the tests.

Can you please take a look and let me know if you're happy with this?

**Comment by mishrsud** [comment]
Hey @mderriey, looks great!
I think there may still be value in continuing this exercise (given that the workshops are paused for the moment) what do you think?

**Pull request closed without merging**
